"""Off-policy Monte Carlo control agent.

Estimates a target policy from episodes generated by an epsilon-soft behaviour
policy. The target policy is deterministic greedy by default (textbook) or
epsilon-soft with a configurable ``target_epsilon`` (soft target variant).
Supports the textbook cumulative weighted-average update and a constant-alpha
importance-weighted update.

Note on learning-rate schedules: a ``LearningRateSchedule`` is consulted *only*
when ``update_mode == "alpha"``. In ``update_mode == "weighted"`` the agent uses
``W / C(s, a)`` -- the weighted-importance-sampling estimator's intrinsic step
size, which already encodes a state-action visit-weighted denominator. Layering
a separate scheduler on top of WIS would double-count that effect, so the
schedule stays inert in weighted mode.
"""

from __future__ import annotations

import random
from collections import defaultdict
from dataclasses import dataclass

import numpy as np

from agents.base_agent import BaseAgent
from agents.learning_rates import ExponentialDecaySchedule, LearningRateSchedule


@dataclass(frozen=True)
class OffPolicyMCEpisodeResult:
    """Per-episode diagnostics returned after weighted MC updates.

    ``alpha``/``alpha_min``/``alpha_max`` are populated only in
    ``update_mode == "alpha"``; they are ``None`` in ``weighted`` mode where
    the WIS estimator's ``W / C(s, a)`` step size is not a schedule the
    trainer can summarise.
    """

    delta_q: float
    total_reward: float
    epsilon: float
    alpha: float | None
    alpha_min: float | None
    alpha_max: float | None
    importance_weight: float


class OffPolicyMCAgent(BaseAgent):
    """Off-policy MC control with an epsilon-soft behaviour policy.

    When ``target_epsilon`` is 0.0 (default), the target policy is
    deterministic greedy and the backward loop breaks at the first
    non-greedy action -- standard textbook behaviour. When
    ``target_epsilon > 0``, the target policy is epsilon-soft so
    ``pi(a|s) > 0`` for all actions, which keeps the importance ratio
    finite past the first non-greedy action. Empirically on this
    grid-world setup the soft-target variant has not outperformed the
    textbook deterministic target, so it is exposed as an option but
    not the default.
    """

    n_actions: int
    gamma: float
    epsilon: float
    epsilon_decay: float
    epsilon_min: float
    target_epsilon: float
    alpha: float | None
    q_init: float
    q_init_noise: float
    update_mode: str
    importance_weight_clip: float | None
    q_table: dict[tuple[int, int], np.ndarray]
    cumulative_weights: dict[tuple[int, int], np.ndarray]
    values: dict[tuple[int, int], float]
    policy: dict[tuple[int, int], int]
    lr_schedule: LearningRateSchedule
    last_episode_mean_alpha: float | None
    last_episode_alpha_min: float | None
    last_episode_alpha_max: float | None

    _episode: list[tuple[tuple[int, int], int, float, float]]
    _rng: random.Random
    _training: bool
    _last_behaviour_probability: float

    def __init__(
        self,
        n_actions: int = 4,
        gamma: float = 0.9,
        epsilon: float = 0.3,
        epsilon_decay: float = 0.9998,
        epsilon_min: float = 0.02,
        target_epsilon: float = 0.0,
        alpha: float = 0.2,
        alpha_decay: float = 0.9998,
        alpha_min: float = 0.02,
        decaying_alpha: bool = True,
        q_init: float = 0.0,
        q_init_noise: float = 1e-6,
        update_mode: str = "weighted",
        importance_weight_clip: float | None = 10.0,
        random_seed: int | None = 0,
        lr_schedule: LearningRateSchedule | None = None,
    ) -> None:
        super().__init__()
        if not 0.0 < epsilon <= 1.0:
            raise ValueError("epsilon must be in (0, 1]")
        if not 0.0 <= epsilon_min <= epsilon:
            raise ValueError("epsilon_min must be in (0, epsilon]")
        if not 0.0 < epsilon_decay <= 1.0:
            raise ValueError("epsilon_decay must be in (0, 1]")
        if not 0.0 <= target_epsilon < 1.0:
            raise ValueError("target_epsilon must be in [0, 1)")
        if target_epsilon >= epsilon:
            raise ValueError(
                "target_epsilon must be strictly less than behaviour epsilon "
                "to keep importance ratios bounded"
            )
        if not 0.0 <= gamma < 1.0:
            raise ValueError("gamma must be in [0, 1)")
        if q_init_noise < 0.0:
            raise ValueError("q_init_noise must be >= 0")
        if update_mode not in {"weighted", "alpha"}:
            raise ValueError("update_mode must be 'weighted' or 'alpha'")
        if importance_weight_clip is not None and importance_weight_clip <= 0.0:
            raise ValueError("importance_weight_clip must be positive when set")

        self.n_actions = n_actions
        self.gamma = gamma
        self.epsilon = epsilon
        self.epsilon_decay = epsilon_decay
        self.epsilon_min = epsilon_min
        self.target_epsilon = target_epsilon
        self.q_init = q_init
        self.q_init_noise = q_init_noise
        self.update_mode = update_mode
        self.importance_weight_clip = importance_weight_clip
        self._rng = random.Random(random_seed)

        # Trainers pass an explicit schedule; legacy callers keep the old
        # alpha/alpha_decay/alpha_min/decaying_alpha surface, which we collapse
        # onto an ExponentialDecaySchedule here. The schedule itself is only
        # consulted in update_mode="alpha"; in weighted mode it stays inert.
        if lr_schedule is None:
            effective_decay = alpha_decay if decaying_alpha else 1.0
            effective_min = alpha_min if decaying_alpha else alpha
            lr_schedule = ExponentialDecaySchedule(
                alpha=alpha, decay=effective_decay, minimum=effective_min,
            )
        self.lr_schedule = lr_schedule

        if update_mode == "alpha":
            self.alpha = self.lr_schedule.get_global_rate()
        else:
            self.alpha = None
        self.last_episode_mean_alpha = None
        self.last_episode_alpha_min = None
        self.last_episode_alpha_max = None

        self.q_table = defaultdict(self._initial_q_values)
        self.cumulative_weights = defaultdict(lambda: np.zeros(self.n_actions, dtype=float))
        self.values = {}
        self.policy = {}

        self._episode = []
        self._training = True
        self._last_behaviour_probability = 1.0

    def _initial_q_values(self) -> np.ndarray:
        """Return initial action values for a newly visited state.

        Tiny seeded noise avoids the all-zero ``argmax`` bias toward action 0
        while keeping the initial values negligible relative to grid rewards.
        """
        if self.q_init_noise == 0.0:
            return np.full(self.n_actions, self.q_init, dtype=float)
        return np.array(
            [
                self.q_init + self._rng.uniform(-self.q_init_noise, self.q_init_noise)
                for _ in range(self.n_actions)
            ],
            dtype=float,
        )

    def _greedy_action(self, state: tuple[int, int]) -> int:
        """Return the deterministic target-policy action for ``state``."""
        return int(np.argmax(self.q_table[state]))

    def _behaviour_probability(self, state: tuple[int, int], action: int) -> float:
        """Probability of ``action`` under the epsilon-soft behaviour policy."""
        probability = self.epsilon / self.n_actions
        if action == self._greedy_action(state):
            probability += 1.0 - self.epsilon
        return probability

    def _target_probability(self, state: tuple[int, int], action: int) -> float:
        """Probability of ``action`` under the target policy.

        Deterministic greedy when ``target_epsilon == 0`` (textbook default).
        Epsilon-soft with ``target_epsilon`` otherwise, guaranteeing
        ``pi(a|s) > 0`` for every action so the backward loop never
        breaks early.
        """
        if self.target_epsilon == 0.0:
            return 1.0 if action == self._greedy_action(state) else 0.0
        probability = self.target_epsilon / self.n_actions
        if action == self._greedy_action(state):
            probability += 1.0 - self.target_epsilon
        return probability

    def take_action(self, state: tuple[int, int]) -> int:
        """Sample from behaviour policy while training, target policy in eval."""
        if not self._training:
            if state in self.policy:
                return self.policy[state]
            return self._greedy_action(state)

        greedy_action = self._greedy_action(state)
        if self._rng.random() < self.epsilon:
            action = self._rng.randrange(self.n_actions)
        else:
            action = greedy_action
        self._last_behaviour_probability = self._behaviour_probability(state, action)
        return action

    def start_episode(self) -> None:
        """Clear the stored trajectory for a new episode."""
        self._episode.clear()
        self._last_behaviour_probability = 1.0

    def record_step(self, state: tuple[int, int], action: int, reward: float) -> None:
        """Record one behaviour-policy transition for later MC backup."""
        self._episode.append((state, action, reward, self._last_behaviour_probability))

    def end_episode(self) -> OffPolicyMCEpisodeResult:
        """Apply weighted importance-sampling updates from the episode."""
        if not self._episode:
            if self.update_mode == "alpha":
                self.lr_schedule.update_episode()
            return OffPolicyMCEpisodeResult(
                delta_q=0.0,
                total_reward=0.0,
                epsilon=self.epsilon,
                alpha=self.lr_schedule.get_global_rate() if self.update_mode == "alpha" else None,
                alpha_min=None,
                alpha_max=None,
                importance_weight=1.0,
            )

        g_return = 0.0
        weight = 1.0
        max_delta = 0.0
        final_weight = 1.0
        episode_alphas: list[float] = []

        for state, action, reward, behaviour_probability in reversed(self._episode):
            g_return = self.gamma * g_return + reward
            self.cumulative_weights[state][action] += weight

            old_q = self.q_table[state][action]
            if self.update_mode == "weighted":
                step_size = weight / self.cumulative_weights[state][action]
            else:
                effective_weight = weight
                if self.importance_weight_clip is not None:
                    effective_weight = min(effective_weight, self.importance_weight_clip)
                applied_alpha = self.lr_schedule.get_rate(state, action)
                episode_alphas.append(applied_alpha)
                step_size = min(1.0, applied_alpha * effective_weight)

            self.q_table[state][action] += step_size * (g_return - old_q)
            max_delta = max(max_delta, abs(self.q_table[state][action] - old_q))

            self.policy[state] = self._greedy_action(state)

            target_prob = self._target_probability(state, action)
            if target_prob == 0.0:
                final_weight = weight
                break

            if behaviour_probability <= 0.0:
                final_weight = weight
                break
            weight *= target_prob / behaviour_probability
            if self.importance_weight_clip is not None:
                weight = min(weight, self.importance_weight_clip)
            final_weight = weight

        self.epsilon = max(self.epsilon_min, self.epsilon * self.epsilon_decay)

        if self.update_mode == "alpha":
            self.lr_schedule.update_episode()
            if episode_alphas:
                self.last_episode_mean_alpha = float(sum(episode_alphas) / len(episode_alphas))
                self.last_episode_alpha_min = float(min(episode_alphas))
                self.last_episode_alpha_max = float(max(episode_alphas))
            else:
                global_rate = self.lr_schedule.get_global_rate()
                self.last_episode_mean_alpha = global_rate
                self.last_episode_alpha_min = global_rate
                self.last_episode_alpha_max = global_rate
            global_rate = self.lr_schedule.get_global_rate()
            self.alpha = (
                global_rate if global_rate is not None else self.last_episode_mean_alpha
            )
        else:
            self.last_episode_mean_alpha = None
            self.last_episode_alpha_min = None
            self.last_episode_alpha_max = None
            self.alpha = None

        total_reward = float(sum(reward for _, _, reward, _ in self._episode))
        self._episode.clear()
        return OffPolicyMCEpisodeResult(
            delta_q=float(max_delta),
            total_reward=total_reward,
            epsilon=float(self.epsilon),
            alpha=self.last_episode_mean_alpha,
            alpha_min=self.last_episode_alpha_min,
            alpha_max=self.last_episode_alpha_max,
            importance_weight=float(final_weight),
        )

    def build_value_and_policy(self) -> None:
        """Populate final value and target-policy dictionaries."""
        self.values = {state: float(np.max(q_values)) for state, q_values in self.q_table.items()}
        self.policy = {state: int(np.argmax(q_values)) for state, q_values in self.q_table.items()}
        self._training = False
