"""Off-policy Monte Carlo control agent.

Estimates a target policy from episodes generated by an epsilon-soft behaviour
policy. The target policy is deterministic greedy by default (textbook) or
epsilon-soft with a configurable ``target_epsilon`` (soft target variant).
Supports the textbook cumulative weighted-average update and a constant-alpha
importance-weighted update.
"""

from __future__ import annotations

import random
from collections import defaultdict
from dataclasses import dataclass

import numpy as np

from agents.base_agent import BaseAgent


@dataclass(frozen=True)
class OffPolicyMCEpisodeResult:
    """Per-episode diagnostics returned after weighted MC updates."""

    delta_q: float
    total_reward: float
    epsilon: float
    alpha: float | None
    importance_weight: float


class OffPolicyMCAgent(BaseAgent):
    """Off-policy MC control with an epsilon-soft behaviour policy.

    When ``target_epsilon`` is 0.0 (default), the target policy is
    deterministic greedy and the backward loop breaks at the first
    non-greedy action — standard textbook behaviour.  When
    ``target_epsilon > 0``, the target policy is epsilon-soft so
    ``pi(a|s) > 0`` for all actions and the entire episode contributes
    to learning, dramatically increasing the effective tail length.
    """

    n_actions: int
    gamma: float
    epsilon: float
    epsilon_decay: float
    epsilon_min: float
    target_epsilon: float
    alpha: float
    alpha_decay: float
    alpha_min: float
    decaying_alpha: bool
    q_init: float
    q_init_noise: float
    update_mode: str
    importance_weight_clip: float | None
    q_table: dict[tuple[int, int], np.ndarray]
    cumulative_weights: dict[tuple[int, int], np.ndarray]
    values: dict[tuple[int, int], float]
    policy: dict[tuple[int, int], int]

    _episode: list[tuple[tuple[int, int], int, float, float]]
    _rng: random.Random
    _training: bool
    _last_behaviour_probability: float

    def __init__(
        self,
        n_actions: int = 4,
        gamma: float = 0.9,
        epsilon: float = 0.3,
        epsilon_decay: float = 0.9998,
        epsilon_min: float = 0.02,
        target_epsilon: float = 0.0,
        alpha: float = 0.2,
        alpha_decay: float = 0.9998,
        alpha_min: float = 0.02,
        decaying_alpha: bool = True,
        q_init: float = 0.0,
        q_init_noise: float = 1e-6,
        update_mode: str = "weighted",
        importance_weight_clip: float | None = 10.0,
        random_seed: int | None = 0,
    ) -> None:
        super().__init__()
        if not 0.0 < epsilon <= 1.0:
            raise ValueError("epsilon must be in (0, 1]")
        if not 0.0 < epsilon_min <= epsilon:
            raise ValueError("epsilon_min must be in (0, epsilon]")
        if not 0.0 < epsilon_decay <= 1.0:
            raise ValueError("epsilon_decay must be in (0, 1]")
        if not 0.0 <= target_epsilon < 1.0:
            raise ValueError("target_epsilon must be in [0, 1)")
        if target_epsilon >= epsilon:
            raise ValueError(
                "target_epsilon must be strictly less than behaviour epsilon "
                "to keep importance ratios bounded"
            )
        if not 0.0 <= gamma < 1.0:
            raise ValueError("gamma must be in [0, 1)")
        if not 0.0 < alpha <= 1.0:
            raise ValueError("alpha must be in (0, 1]")
        if not 0.0 <= alpha_min <= alpha:
            raise ValueError("alpha_min must be in [0, alpha]")
        if not 0.0 < alpha_decay <= 1.0:
            raise ValueError("alpha_decay must be in (0, 1]")
        if q_init_noise < 0.0:
            raise ValueError("q_init_noise must be >= 0")
        if update_mode not in {"weighted", "alpha"}:
            raise ValueError("update_mode must be 'weighted' or 'alpha'")
        if importance_weight_clip is not None and importance_weight_clip <= 0.0:
            raise ValueError("importance_weight_clip must be positive when set")

        self.n_actions = n_actions
        self.gamma = gamma
        self.epsilon = epsilon
        self.epsilon_decay = epsilon_decay
        self.epsilon_min = epsilon_min
        self.target_epsilon = target_epsilon
        self.alpha = alpha
        self.alpha_decay = alpha_decay
        self.alpha_min = alpha_min
        self.decaying_alpha = decaying_alpha
        self.q_init = q_init
        self.q_init_noise = q_init_noise
        self.update_mode = update_mode
        self.importance_weight_clip = importance_weight_clip
        self._rng = random.Random(random_seed)

        self.q_table = defaultdict(self._initial_q_values)
        self.cumulative_weights = defaultdict(lambda: np.zeros(self.n_actions, dtype=float))
        self.values = {}
        self.policy = {}

        self._episode = []
        self._training = True
        self._last_behaviour_probability = 1.0

    def _initial_q_values(self) -> np.ndarray:
        """Return initial action values for a newly visited state.

        Tiny seeded noise avoids the all-zero ``argmax`` bias toward action 0
        while keeping the initial values negligible relative to grid rewards.
        """
        if self.q_init_noise == 0.0:
            return np.full(self.n_actions, self.q_init, dtype=float)
        return np.array(
            [
                self.q_init + self._rng.uniform(-self.q_init_noise, self.q_init_noise)
                for _ in range(self.n_actions)
            ],
            dtype=float,
        )

    def _greedy_action(self, state: tuple[int, int]) -> int:
        """Return the deterministic target-policy action for ``state``."""
        return int(np.argmax(self.q_table[state]))

    def _behaviour_probability(self, state: tuple[int, int], action: int) -> float:
        """Probability of ``action`` under the epsilon-soft behaviour policy."""
        probability = self.epsilon / self.n_actions
        if action == self._greedy_action(state):
            probability += 1.0 - self.epsilon
        return probability

    def _target_probability(self, state: tuple[int, int], action: int) -> float:
        """Probability of ``action`` under the target policy.

        Deterministic greedy when ``target_epsilon == 0`` (textbook default).
        Epsilon-soft with ``target_epsilon`` otherwise, guaranteeing
        ``pi(a|s) > 0`` for every action so the backward loop never
        breaks early.
        """
        if self.target_epsilon == 0.0:
            return 1.0 if action == self._greedy_action(state) else 0.0
        probability = self.target_epsilon / self.n_actions
        if action == self._greedy_action(state):
            probability += 1.0 - self.target_epsilon
        return probability

    def take_action(self, state: tuple[int, int]) -> int:
        """Sample from behaviour policy while training, target policy in eval."""
        if not self._training:
            if state in self.policy:
                return self.policy[state]
            return self._greedy_action(state)

        greedy_action = self._greedy_action(state)
        if self._rng.random() < self.epsilon:
            action = self._rng.randrange(self.n_actions)
        else:
            action = greedy_action
        self._last_behaviour_probability = self._behaviour_probability(state, action)
        return action

    def start_episode(self) -> None:
        """Clear the stored trajectory for a new episode."""
        self._episode.clear()
        self._last_behaviour_probability = 1.0

    def record_step(self, state: tuple[int, int], action: int, reward: float) -> None:
        """Record one behaviour-policy transition for later MC backup."""
        self._episode.append((state, action, reward, self._last_behaviour_probability))

    def end_episode(self) -> OffPolicyMCEpisodeResult:
        """Apply weighted importance-sampling updates from the episode."""
        if not self._episode:
            return OffPolicyMCEpisodeResult(
                delta_q=0.0,
                total_reward=0.0,
                epsilon=self.epsilon,
                alpha=self.alpha if self.update_mode == "alpha" else None,
                importance_weight=1.0,
            )

        g_return = 0.0
        weight = 1.0
        max_delta = 0.0
        final_weight = 1.0

        for state, action, reward, behaviour_probability in reversed(self._episode):
            g_return = self.gamma * g_return + reward
            self.cumulative_weights[state][action] += weight

            old_q = self.q_table[state][action]
            if self.update_mode == "weighted":
                step_size = weight / self.cumulative_weights[state][action]
            else:
                effective_weight = weight
                if self.importance_weight_clip is not None:
                    effective_weight = min(effective_weight, self.importance_weight_clip)
                step_size = min(1.0, self.alpha * effective_weight)

            self.q_table[state][action] += step_size * (g_return - old_q)
            max_delta = max(max_delta, abs(self.q_table[state][action] - old_q))

            self.policy[state] = self._greedy_action(state)

            target_prob = self._target_probability(state, action)
            if target_prob == 0.0:
                final_weight = weight
                break

            if behaviour_probability <= 0.0:
                final_weight = weight
                break
            weight *= target_prob / behaviour_probability
            if self.importance_weight_clip is not None:
                weight = min(weight, self.importance_weight_clip)
            final_weight = weight

        self.epsilon = max(self.epsilon_min, self.epsilon * self.epsilon_decay)
        if self.update_mode == "alpha" and self.decaying_alpha:
            self.alpha = max(self.alpha_min, self.alpha * self.alpha_decay)
        total_reward = float(sum(reward for _, _, reward, _ in self._episode))
        self._episode.clear()
        return OffPolicyMCEpisodeResult(
            delta_q=float(max_delta),
            total_reward=total_reward,
            epsilon=float(self.epsilon),
            alpha=float(self.alpha) if self.update_mode == "alpha" else None,
            importance_weight=float(final_weight),
        )

    def build_value_and_policy(self) -> None:
        """Populate final value and target-policy dictionaries."""
        self.values = {state: float(np.max(q_values)) for state, q_values in self.q_table.items()}
        self.policy = {state: int(np.argmax(q_values)) for state, q_values in self.q_table.items()}
        self._training = False
